import random

#The following sets of variables will, upon being run, generate a random letter. The first two will create a random uppercase letter while the next set will create a lowercase letter. This is achieved using randomly generated ascii codes.

upperCaseLetterOne = chr(random.randint(65, 90))
upperCaseLetterTwo = chr(random.randint(65, 90))

lowerCaseLetterOne = chr(random.randint(97, 122))
lowerCaseLetterTwo = chr(random.randint(97, 122))

#The following variables will create the rest of the random characters. The first two will result in random numbers while the second set will generate random punctuation symbols($, @ and so on).

digitOne = chr(random.randint(48, 57))
digitTwo = chr(random.randint(48, 57))

punctuationSignOne = chr(random.randint(33, 152))
punctuationSignTwo = chr(random.randint(33, 152))

#This function is here to shuffle around the characters in the eventual output. It will take a string and rotate the order of the letters around to create a random output.

def shuffle(string):
  tempList = list(string)
  random.shuffle(tempList)
  return ''.join(tempList)

#Finally, the password is generated by combining the above variables before being shuffled using the function and printed to the console. It should be noted that currently the length of the password and how many times each type of character
#appears is hardcoded. This may be changed later to incorporate more randomness but it is set by default at present. It also only exports to the console and does not print to a text file. Yet...

password = upperCaseLetterOne + upperCaseLetterTwo + lowerCaseLetterOne + lowerCaseLetterTwo + digitOne + digitTwo + punctuationSignOne + punctuationSignTwo
shuffle(password)
print(f'Your new password is {password}')